name: Playwright Daily Reports

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'
    # Daily at UTC 00:00
    # Around 5:30 AM India time

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  test:

    timeout-minutes: 120

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup NodeJS
        uses: actions/setup-node@v4

        with:
          node-version: lts/*


      - name: Install dependencies
        run: npm ci


      - name: Install browsers
        run: npx playwright install --with-deps


      - name: Run tests
        run: |

          npx playwright test --workers=1

        continue-on-error: true



      - name: Generate Allure report
        run: |

          npx allure generate allure-results \
          --clean \
          -o reports/allure-report



      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4

        with:

          name: html-report

          path: reports/html-report



      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4

        with:

          name: allure-report

          path: reports/allure-report




      - name: Commit updated reports
        run: |

          git config --global user.email "actions@github.com"

          git config --global user.name "github-actions"

          git add reports/

          git commit -m "Daily report update" || echo "No changes"

          git push




      - name: Deploy reports to GitHub Pages

        uses: peaceiris/actions-gh-pages@v3

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_branch: gh-pages

          publish_dir: reports/allure-report